displayName=Green Screen
author=Ezra-Black
support=https://github.com/Ezra-Black/minimap-green-plugin
description=Adds a greenscreen, useful for content creators. Original author: I Yam Jeremy
tags=minimap,streaming,chroma key,greenscreen,overlay
plugins=com.greenscreen.GreenScreenPlugin
